//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QRealModel", "LogicalInstanceProperties", "LogicalInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.LogicalInstance), "InstanceProperty", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.InstanceProperty), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "GraphicToLogical", "GraphicInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.GraphicInstance), "LogicalInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.LogicalInstance), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "RootInstanceEdgeInstance", "RootInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.RootInstance), "EdgeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.EdgeInstance), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "EdgesFromNode", "NodeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QReal.Web.Database.NodeInstance), "EdgeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.EdgeInstance), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "EdgesToNode", "NodeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QReal.Web.Database.NodeInstance), "EdgeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.EdgeInstance), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "EdgeInstanceGeometryInformation", "EdgeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QReal.Web.Database.EdgeInstance), "GeometryInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.GeometryInformation), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "NodeInstanceGeometryInformation", "NodeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QReal.Web.Database.NodeInstance), "GeometryInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.GeometryInformation), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "NodeParents", "ParentableInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(QReal.Web.Database.ParentableInstance), "NodeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.NodeInstance), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "GraphicInstanceParentableInstanceInheritance", "GraphicInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.GraphicInstance), "ParentableInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.ParentableInstance), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "GraphicInstanceEdgeInstanceInheritance", "GraphicInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.GraphicInstance), "EdgeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.EdgeInstance), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "ParentableInstanceRootInstanceInheritance", "ParentableInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.ParentableInstance), "RootInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.RootInstance), true)]
[assembly: EdmRelationshipAttribute("QRealModel", "ParentableInstanceNodeInstanceInheritance", "ParentableInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(QReal.Web.Database.ParentableInstance), "NodeInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QReal.Web.Database.NodeInstance), true)]

#endregion

namespace QReal.Web.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QRealEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QRealEntities object using the connection string found in the 'QRealEntities' section of the application configuration file.
        /// </summary>
        public QRealEntities() : base("name=QRealEntities", "QRealEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QRealEntities object.
        /// </summary>
        public QRealEntities(string connectionString) : base(connectionString, "QRealEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QRealEntities object.
        /// </summary>
        public QRealEntities(EntityConnection connection) : base(connection, "QRealEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LogicalInstance> LogicalInstances
        {
            get
            {
                if ((_LogicalInstances == null))
                {
                    _LogicalInstances = base.CreateObjectSet<LogicalInstance>("LogicalInstances");
                }
                return _LogicalInstances;
            }
        }
        private ObjectSet<LogicalInstance> _LogicalInstances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InstanceProperty> InstanceProperties
        {
            get
            {
                if ((_InstanceProperties == null))
                {
                    _InstanceProperties = base.CreateObjectSet<InstanceProperty>("InstanceProperties");
                }
                return _InstanceProperties;
            }
        }
        private ObjectSet<InstanceProperty> _InstanceProperties;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GraphicInstance> GraphicInstances
        {
            get
            {
                if ((_GraphicInstances == null))
                {
                    _GraphicInstances = base.CreateObjectSet<GraphicInstance>("GraphicInstances");
                }
                return _GraphicInstances;
            }
        }
        private ObjectSet<GraphicInstance> _GraphicInstances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ParentableInstance> ParentableInstanceSet
        {
            get
            {
                if ((_ParentableInstanceSet == null))
                {
                    _ParentableInstanceSet = base.CreateObjectSet<ParentableInstance>("ParentableInstanceSet");
                }
                return _ParentableInstanceSet;
            }
        }
        private ObjectSet<ParentableInstance> _ParentableInstanceSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RootInstance> RootInstanceSet
        {
            get
            {
                if ((_RootInstanceSet == null))
                {
                    _RootInstanceSet = base.CreateObjectSet<RootInstance>("RootInstanceSet");
                }
                return _RootInstanceSet;
            }
        }
        private ObjectSet<RootInstance> _RootInstanceSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NodeInstance> NodeInstanceSet
        {
            get
            {
                if ((_NodeInstanceSet == null))
                {
                    _NodeInstanceSet = base.CreateObjectSet<NodeInstance>("NodeInstanceSet");
                }
                return _NodeInstanceSet;
            }
        }
        private ObjectSet<NodeInstance> _NodeInstanceSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EdgeInstance> EdgeInstanceSet
        {
            get
            {
                if ((_EdgeInstanceSet == null))
                {
                    _EdgeInstanceSet = base.CreateObjectSet<EdgeInstance>("EdgeInstanceSet");
                }
                return _EdgeInstanceSet;
            }
        }
        private ObjectSet<EdgeInstance> _EdgeInstanceSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GeometryInformation> GeometryInformationSet
        {
            get
            {
                if ((_GeometryInformationSet == null))
                {
                    _GeometryInformationSet = base.CreateObjectSet<GeometryInformation>("GeometryInformationSet");
                }
                return _GeometryInformationSet;
            }
        }
        private ObjectSet<GeometryInformation> _GeometryInformationSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LogicalInstances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogicalInstances(LogicalInstance logicalInstance)
        {
            base.AddObject("LogicalInstances", logicalInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InstanceProperties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInstanceProperties(InstanceProperty instanceProperty)
        {
            base.AddObject("InstanceProperties", instanceProperty);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GraphicInstances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGraphicInstances(GraphicInstance graphicInstance)
        {
            base.AddObject("GraphicInstances", graphicInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ParentableInstanceSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParentableInstanceSet(ParentableInstance parentableInstance)
        {
            base.AddObject("ParentableInstanceSet", parentableInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RootInstanceSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRootInstanceSet(RootInstance rootInstance)
        {
            base.AddObject("RootInstanceSet", rootInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NodeInstanceSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNodeInstanceSet(NodeInstance nodeInstance)
        {
            base.AddObject("NodeInstanceSet", nodeInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EdgeInstanceSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEdgeInstanceSet(EdgeInstance edgeInstance)
        {
            base.AddObject("EdgeInstanceSet", edgeInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GeometryInformationSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGeometryInformationSet(GeometryInformation geometryInformation)
        {
            base.AddObject("GeometryInformationSet", geometryInformation);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QRealModel", Name="EdgeInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EdgeInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EdgeInstance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="parentId">Initial value of the ParentId property.</param>
        /// <param name="inheritanceId">Initial value of the InheritanceId property.</param>
        public static EdgeInstance CreateEdgeInstance(global::System.Int32 id, global::System.Int32 parentId, global::System.Int32 inheritanceId)
        {
            EdgeInstance edgeInstance = new EdgeInstance();
            edgeInstance.Id = id;
            edgeInstance.ParentId = parentId;
            edgeInstance.InheritanceId = inheritanceId;
            return edgeInstance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private global::System.Int32 _ParentId;
        partial void OnParentIdChanging(global::System.Int32 value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NodeFromId
        {
            get
            {
                return _NodeFromId;
            }
            set
            {
                OnNodeFromIdChanging(value);
                ReportPropertyChanging("NodeFromId");
                _NodeFromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeFromId");
                OnNodeFromIdChanged();
            }
        }
        private Nullable<global::System.Int32> _NodeFromId;
        partial void OnNodeFromIdChanging(Nullable<global::System.Int32> value);
        partial void OnNodeFromIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NodeToId
        {
            get
            {
                return _NodeToId;
            }
            set
            {
                OnNodeToIdChanging(value);
                ReportPropertyChanging("NodeToId");
                _NodeToId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeToId");
                OnNodeToIdChanged();
            }
        }
        private Nullable<global::System.Int32> _NodeToId;
        partial void OnNodeToIdChanging(Nullable<global::System.Int32> value);
        partial void OnNodeToIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PortFrom
        {
            get
            {
                return _PortFrom;
            }
            set
            {
                OnPortFromChanging(value);
                ReportPropertyChanging("PortFrom");
                _PortFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortFrom");
                OnPortFromChanged();
            }
        }
        private Nullable<global::System.Double> _PortFrom;
        partial void OnPortFromChanging(Nullable<global::System.Double> value);
        partial void OnPortFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PortTo
        {
            get
            {
                return _PortTo;
            }
            set
            {
                OnPortToChanging(value);
                ReportPropertyChanging("PortTo");
                _PortTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PortTo");
                OnPortToChanged();
            }
        }
        private Nullable<global::System.Double> _PortTo;
        partial void OnPortToChanging(Nullable<global::System.Double> value);
        partial void OnPortToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InheritanceId
        {
            get
            {
                return _InheritanceId;
            }
            set
            {
                OnInheritanceIdChanging(value);
                ReportPropertyChanging("InheritanceId");
                _InheritanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InheritanceId");
                OnInheritanceIdChanged();
            }
        }
        private global::System.Int32 _InheritanceId;
        partial void OnInheritanceIdChanging(global::System.Int32 value);
        partial void OnInheritanceIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "RootInstanceEdgeInstance", "RootInstance")]
        public RootInstance Parent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootInstance>("QRealModel.RootInstanceEdgeInstance", "RootInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootInstance>("QRealModel.RootInstanceEdgeInstance", "RootInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RootInstance> ParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootInstance>("QRealModel.RootInstanceEdgeInstance", "RootInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RootInstance>("QRealModel.RootInstanceEdgeInstance", "RootInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "EdgesFromNode", "NodeInstance")]
        public NodeInstance NodeFrom
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeInstance>("QRealModel.EdgesFromNode", "NodeInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeInstance>("QRealModel.EdgesFromNode", "NodeInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NodeInstance> NodeFromReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeInstance>("QRealModel.EdgesFromNode", "NodeInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NodeInstance>("QRealModel.EdgesFromNode", "NodeInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "EdgesToNode", "NodeInstance")]
        public NodeInstance NodeTo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeInstance>("QRealModel.EdgesToNode", "NodeInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeInstance>("QRealModel.EdgesToNode", "NodeInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NodeInstance> NodeToReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeInstance>("QRealModel.EdgesToNode", "NodeInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NodeInstance>("QRealModel.EdgesToNode", "NodeInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "EdgeInstanceGeometryInformation", "GeometryInformation")]
        public GeometryInformation GeometryInformation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeometryInformation>("QRealModel.EdgeInstanceGeometryInformation", "GeometryInformation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeometryInformation>("QRealModel.EdgeInstanceGeometryInformation", "GeometryInformation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GeometryInformation> GeometryInformationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeometryInformation>("QRealModel.EdgeInstanceGeometryInformation", "GeometryInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GeometryInformation>("QRealModel.EdgeInstanceGeometryInformation", "GeometryInformation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "GraphicInstanceEdgeInstanceInheritance", "GraphicInstance")]
        public GraphicInstance InheritanceParent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GraphicInstance>("QRealModel.GraphicInstanceEdgeInstanceInheritance", "GraphicInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GraphicInstance>("QRealModel.GraphicInstanceEdgeInstanceInheritance", "GraphicInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GraphicInstance> InheritanceParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GraphicInstance>("QRealModel.GraphicInstanceEdgeInstanceInheritance", "GraphicInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GraphicInstance>("QRealModel.GraphicInstanceEdgeInstanceInheritance", "GraphicInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QRealModel", Name="GeometryInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GeometryInformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GeometryInformation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="x">Initial value of the X property.</param>
        /// <param name="y">Initial value of the Y property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        public static GeometryInformation CreateGeometryInformation(global::System.Int32 id, global::System.Double x, global::System.Double y, global::System.Double width, global::System.Double height)
        {
            GeometryInformation geometryInformation = new GeometryInformation();
            geometryInformation.Id = id;
            geometryInformation.X = x;
            geometryInformation.Y = y;
            geometryInformation.Width = width;
            geometryInformation.Height = height;
            return geometryInformation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double X
        {
            get
            {
                return _X;
            }
            set
            {
                OnXChanging(value);
                ReportPropertyChanging("X");
                _X = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("X");
                OnXChanged();
            }
        }
        private global::System.Double _X;
        partial void OnXChanging(global::System.Double value);
        partial void OnXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Y
        {
            get
            {
                return _Y;
            }
            set
            {
                OnYChanging(value);
                ReportPropertyChanging("Y");
                _Y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Y");
                OnYChanged();
            }
        }
        private global::System.Double _Y;
        partial void OnYChanging(global::System.Double value);
        partial void OnYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Double _Width;
        partial void OnWidthChanging(global::System.Double value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Double _Height;
        partial void OnHeightChanging(global::System.Double value);
        partial void OnHeightChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QRealModel", Name="GraphicInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GraphicInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GraphicInstance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="logicalInstanceId">Initial value of the LogicalInstanceId property.</param>
        public static GraphicInstance CreateGraphicInstance(global::System.Int32 id, global::System.Int32 logicalInstanceId)
        {
            GraphicInstance graphicInstance = new GraphicInstance();
            graphicInstance.Id = id;
            graphicInstance.LogicalInstanceId = logicalInstanceId;
            return graphicInstance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogicalInstanceId
        {
            get
            {
                return _LogicalInstanceId;
            }
            set
            {
                OnLogicalInstanceIdChanging(value);
                ReportPropertyChanging("LogicalInstanceId");
                _LogicalInstanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LogicalInstanceId");
                OnLogicalInstanceIdChanged();
            }
        }
        private global::System.Int32 _LogicalInstanceId;
        partial void OnLogicalInstanceIdChanging(global::System.Int32 value);
        partial void OnLogicalInstanceIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "GraphicToLogical", "LogicalInstance")]
        public LogicalInstance LogicalInstance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LogicalInstance>("QRealModel.GraphicToLogical", "LogicalInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LogicalInstance>("QRealModel.GraphicToLogical", "LogicalInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LogicalInstance> LogicalInstanceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LogicalInstance>("QRealModel.GraphicToLogical", "LogicalInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LogicalInstance>("QRealModel.GraphicToLogical", "LogicalInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "GraphicInstanceParentableInstanceInheritance", "ParentableInstance")]
        public EntityCollection<ParentableInstance> ParentableInstanceInheritance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ParentableInstance>("QRealModel.GraphicInstanceParentableInstanceInheritance", "ParentableInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ParentableInstance>("QRealModel.GraphicInstanceParentableInstanceInheritance", "ParentableInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "GraphicInstanceEdgeInstanceInheritance", "EdgeInstance")]
        public EntityCollection<EdgeInstance> EdgeInstance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EdgeInstance>("QRealModel.GraphicInstanceEdgeInstanceInheritance", "EdgeInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EdgeInstance>("QRealModel.GraphicInstanceEdgeInstanceInheritance", "EdgeInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QRealModel", Name="InstanceProperty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InstanceProperty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InstanceProperty object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="logicalInstanceId">Initial value of the LogicalInstanceId property.</param>
        public static InstanceProperty CreateInstanceProperty(global::System.Int32 id, global::System.String name, global::System.Int32 logicalInstanceId)
        {
            InstanceProperty instanceProperty = new InstanceProperty();
            instanceProperty.Id = id;
            instanceProperty.Name = name;
            instanceProperty.LogicalInstanceId = logicalInstanceId;
            return instanceProperty;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogicalInstanceId
        {
            get
            {
                return _LogicalInstanceId;
            }
            set
            {
                OnLogicalInstanceIdChanging(value);
                ReportPropertyChanging("LogicalInstanceId");
                _LogicalInstanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LogicalInstanceId");
                OnLogicalInstanceIdChanged();
            }
        }
        private global::System.Int32 _LogicalInstanceId;
        partial void OnLogicalInstanceIdChanging(global::System.Int32 value);
        partial void OnLogicalInstanceIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "LogicalInstanceProperties", "LogicalInstance")]
        public LogicalInstance LogicalInstance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LogicalInstance>("QRealModel.LogicalInstanceProperties", "LogicalInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LogicalInstance>("QRealModel.LogicalInstanceProperties", "LogicalInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LogicalInstance> LogicalInstanceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LogicalInstance>("QRealModel.LogicalInstanceProperties", "LogicalInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LogicalInstance>("QRealModel.LogicalInstanceProperties", "LogicalInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QRealModel", Name="LogicalInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LogicalInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LogicalInstance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static LogicalInstance CreateLogicalInstance(global::System.Int32 id, global::System.String type, global::System.String name)
        {
            LogicalInstance logicalInstance = new LogicalInstance();
            logicalInstance.Id = id;
            logicalInstance.Type = type;
            logicalInstance.Name = name;
            return logicalInstance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "LogicalInstanceProperties", "InstanceProperty")]
        public EntityCollection<InstanceProperty> InstanceProperties
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InstanceProperty>("QRealModel.LogicalInstanceProperties", "InstanceProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InstanceProperty>("QRealModel.LogicalInstanceProperties", "InstanceProperty", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "GraphicToLogical", "GraphicInstance")]
        public EntityCollection<GraphicInstance> GraphicInstance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GraphicInstance>("QRealModel.GraphicToLogical", "GraphicInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GraphicInstance>("QRealModel.GraphicToLogical", "GraphicInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QRealModel", Name="NodeInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NodeInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NodeInstance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="inheritanceId">Initial value of the InheritanceId property.</param>
        public static NodeInstance CreateNodeInstance(global::System.Int32 id, global::System.Int32 inheritanceId)
        {
            NodeInstance nodeInstance = new NodeInstance();
            nodeInstance.Id = id;
            nodeInstance.InheritanceId = inheritanceId;
            return nodeInstance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InheritanceId
        {
            get
            {
                return _InheritanceId;
            }
            set
            {
                OnInheritanceIdChanging(value);
                ReportPropertyChanging("InheritanceId");
                _InheritanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InheritanceId");
                OnInheritanceIdChanged();
            }
        }
        private global::System.Int32 _InheritanceId;
        partial void OnInheritanceIdChanging(global::System.Int32 value);
        partial void OnInheritanceIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "EdgesFromNode", "EdgeInstance")]
        public EntityCollection<EdgeInstance> EdgesFrom
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EdgeInstance>("QRealModel.EdgesFromNode", "EdgeInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EdgeInstance>("QRealModel.EdgesFromNode", "EdgeInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "EdgesToNode", "EdgeInstance")]
        public EntityCollection<EdgeInstance> EdgesTo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EdgeInstance>("QRealModel.EdgesToNode", "EdgeInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EdgeInstance>("QRealModel.EdgesToNode", "EdgeInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "NodeInstanceGeometryInformation", "GeometryInformation")]
        public GeometryInformation GeometryInformation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeometryInformation>("QRealModel.NodeInstanceGeometryInformation", "GeometryInformation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeometryInformation>("QRealModel.NodeInstanceGeometryInformation", "GeometryInformation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GeometryInformation> GeometryInformationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GeometryInformation>("QRealModel.NodeInstanceGeometryInformation", "GeometryInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GeometryInformation>("QRealModel.NodeInstanceGeometryInformation", "GeometryInformation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "NodeParents", "ParentableInstance")]
        public ParentableInstance Parent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.NodeParents", "ParentableInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.NodeParents", "ParentableInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ParentableInstance> ParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.NodeParents", "ParentableInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ParentableInstance>("QRealModel.NodeParents", "ParentableInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "ParentableInstanceNodeInstanceInheritance", "ParentableInstance")]
        public ParentableInstance InheritanceParent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.ParentableInstanceNodeInstanceInheritance", "ParentableInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.ParentableInstanceNodeInstanceInheritance", "ParentableInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ParentableInstance> InheritanceParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.ParentableInstanceNodeInstanceInheritance", "ParentableInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ParentableInstance>("QRealModel.ParentableInstanceNodeInstanceInheritance", "ParentableInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QRealModel", Name="ParentableInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ParentableInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ParentableInstance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="inheritanceId">Initial value of the InheritanceId property.</param>
        public static ParentableInstance CreateParentableInstance(global::System.Int32 id, global::System.Int32 inheritanceId)
        {
            ParentableInstance parentableInstance = new ParentableInstance();
            parentableInstance.Id = id;
            parentableInstance.InheritanceId = inheritanceId;
            return parentableInstance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InheritanceId
        {
            get
            {
                return _InheritanceId;
            }
            set
            {
                OnInheritanceIdChanging(value);
                ReportPropertyChanging("InheritanceId");
                _InheritanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InheritanceId");
                OnInheritanceIdChanged();
            }
        }
        private global::System.Int32 _InheritanceId;
        partial void OnInheritanceIdChanging(global::System.Int32 value);
        partial void OnInheritanceIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "NodeParents", "NodeInstance")]
        public EntityCollection<NodeInstance> NodeChildren
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NodeInstance>("QRealModel.NodeParents", "NodeInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NodeInstance>("QRealModel.NodeParents", "NodeInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "GraphicInstanceParentableInstanceInheritance", "GraphicInstance")]
        public GraphicInstance InheritanceParent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GraphicInstance>("QRealModel.GraphicInstanceParentableInstanceInheritance", "GraphicInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GraphicInstance>("QRealModel.GraphicInstanceParentableInstanceInheritance", "GraphicInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GraphicInstance> InheritanceParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GraphicInstance>("QRealModel.GraphicInstanceParentableInstanceInheritance", "GraphicInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GraphicInstance>("QRealModel.GraphicInstanceParentableInstanceInheritance", "GraphicInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "ParentableInstanceRootInstanceInheritance", "RootInstance")]
        public EntityCollection<RootInstance> RootInstanceInheritance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RootInstance>("QRealModel.ParentableInstanceRootInstanceInheritance", "RootInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RootInstance>("QRealModel.ParentableInstanceRootInstanceInheritance", "RootInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QRealModel", Name="RootInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RootInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RootInstance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="inheritanceId">Initial value of the InheritanceId property.</param>
        public static RootInstance CreateRootInstance(global::System.Int32 id, global::System.Int32 inheritanceId)
        {
            RootInstance rootInstance = new RootInstance();
            rootInstance.Id = id;
            rootInstance.InheritanceId = inheritanceId;
            return rootInstance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InheritanceId
        {
            get
            {
                return _InheritanceId;
            }
            set
            {
                OnInheritanceIdChanging(value);
                ReportPropertyChanging("InheritanceId");
                _InheritanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InheritanceId");
                OnInheritanceIdChanged();
            }
        }
        private global::System.Int32 _InheritanceId;
        partial void OnInheritanceIdChanging(global::System.Int32 value);
        partial void OnInheritanceIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "RootInstanceEdgeInstance", "EdgeInstance")]
        public EntityCollection<EdgeInstance> EdgeChildren
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EdgeInstance>("QRealModel.RootInstanceEdgeInstance", "EdgeInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EdgeInstance>("QRealModel.RootInstanceEdgeInstance", "EdgeInstance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QRealModel", "ParentableInstanceRootInstanceInheritance", "ParentableInstance")]
        public ParentableInstance InheritanceParent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.ParentableInstanceRootInstanceInheritance", "ParentableInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.ParentableInstanceRootInstanceInheritance", "ParentableInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ParentableInstance> InheritanceParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParentableInstance>("QRealModel.ParentableInstanceRootInstanceInheritance", "ParentableInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ParentableInstance>("QRealModel.ParentableInstanceRootInstanceInheritance", "ParentableInstance", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
